### ISSUE TITLE
Cookie cross-site security warning

### ISSUE THREAD

**Issue by dtwist** [Alquemie/gf-campaign-fields#1]
Firefox is warning that cookies set by the gf campaign fields plugin will soon be rejected because they are setting the `SameSite` attribute to `None`. The fix is to either add the `Secure` attribute or set the `SameSite` attribute to `strict`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by alquemiemktg** [comment]
@dtwist I have updated the cookie code to set SameSite and Secure.  Give version 2.4.0 a try and see if it resolves your issue.
